### ISSUE TITLE
Using When,Then throws  steps-unimplemented issue in the execution execution

### ISSUE THREAD

**Issue by qarampage** [lqthang2204/Selenium-with-python-behave#16]
Hi @lqthang2204 

I found your repo quite interesting and impressive. Out of several selenium behave repo, yours was the only repo where I had to make minor tweaks to execute on my machine. 
While I was verifying this repo and trying to execute this Test Script, I found that if I use When/Then in the Feature file scenario, it throws step-unimplemented error. But when I keep Given and And, it works fine.
1. Could you please let me know how to resolve this error ?
2. I have a few suggestions, I would like to contact with you over chat/ call so that I can explain in more details. how to contact you ?

@testLogin
Feature: navigate URL
  Scenario: test login page
    Given I navigate to url have index 1
    **When** I change the page spec to LoginPage
    **Then** I wait for element user-field to be DISPLAYED
    And I wait for element pass-field to be DISPLAYED
    **Then** I save text for element login-form-title with key "title"
    And I type "KEY.title" into element user-field
    And I perform login-page-two action with override values
      | Field      | Value    |
      | user-field | Admin    |
      | pass-field | KEY.title |
    And I wait for element error-message to be DISPLAYED

**Error :**

Failing scenarios:
  features/Login.feature:3  test login page

0 features passed, 1 failed, 0 skipped
0 scenarios passed, 1 failed, 0 skipped
1 step passed, 0 failed, 0 skipped, 31 undefined
Took 0m3.368s

You can implement step definitions for undefined steps with these snippets:

@when(u'I change the page spec to LoginPage')
def step_impl(context):
    raise NotImplementedError(u'STEP: When I change the page spec to LoginPage')

@when(u'I wait for element user-field to be DISPLAYED')
def step_impl(context):
    raise NotImplementedError(u'STEP: When I wait for element user-field to be DISPLAYED')

and rest other steps throw error with @when prefix

**Comment by lqthang2204** [comment]
Hi, @qarampage Thank you for reporting the issue. I fixed it in PR https://github.com/lqthang2204/Selenium-with-python-behave/pull/17. 
You can contact me through Skype (quangthangle1402).

**Comment by qarampage** [comment]
Thanks , it worked
