### ISSUE TITLE
BUG - Found when the sequence of Test Step has Dict Key creation but not used in Type command

### ISSUE THREAD

**Issue by qarampage** [lqthang2204/Selenium-with-python-behave#18]
For the highlighted sequence of Test Steps, where we have a type command but the keys isn't available in Dictionary
<img width="602" alt="image" src="https://github.com/lqthang2204/Selenium-with-python-behave/assets/16265665/8019176d-1a63-4ac7-a267-80c84fd64e9e">

**Below error is encountered**
   File "/Users/selenium-behave/Utilities/action_web.py", line 200, in action_page
          if dict_save_value[value] is not None:
      KeyError: 'Admin12dsdsds3'

**Login Feature Step sequence which failed**
<img width="652" alt="image" src="https://github.com/lqthang2204/Selenium-with-python-behave/assets/16265665/475446fd-576d-4c24-8f4c-0d1fbd82859a">

**Code Fix required**
<img width="1243" alt="image" src="https://github.com/lqthang2204/Selenium-with-python-behave/assets/16265665/313d0ac0-0c58-4532-887c-1c4c89926eef">

I tried pushing a Branch but I was getting permission 403 error.

**Comment by lqthang2204** [comment]
Hi @qarampage, I added your account as a collaborator to the repository. Please check your email and try to push again

**Comment by qarampage** [comment]
> Hi @qarampage, I added your account as a collaborator to the repository. Please check your email and try to push again

Hi,
 It didn't work for me .I will report it directly to you

**Comment by lqthang2204** [comment]
fixed and merged in PR https://github.com/lqthang2204/Selenium-with-python-behave/pull/19
